name: Actualizar Página

on:
  schedule:
    - cron: '*/1 * * * *'  # Ejecutar cada minuto

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run script
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        python script.py
        git config --global user.name 'FerAmbriz'
        git config --global user.email 'fernandoambrizbarrera@gmail.com'
        git add index.html
        git commit -m "Actualizar página"
        git push https://$GH_TOKEN@github.com/FerAmbriz/TestPagina.git
