name: Scheduled Job

on:
  schedule:
    - cron: '*/1 * * * *' # Esto se ejecuta cada minuto
      #- cron: '0 0 * * *' # Esto se ejecuta todos los días a medianoche
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a script
      run: echo "La hora actual es $(date)" > ../../index.html
